### ISSUE TITLE
Logo/design proposal

### ISSUE THREAD

**Issue by jbeguna04** [Abdallah-Abdelazim/My-Notes#1]
Please allow me to submit a design of your application a new logo/icon.  Hoping for your positive respone thank you!

**Comment by Abdallah-Abdelazim** [comment]
Ok, sure you can

**Comment by Abdallah-Abdelazim** [comment]
Just make a pull request and I will approve it

**Comment by jbeguna04** [comment]
#### Hi. I made now the design of your app
![cfghdfgf](https://user-images.githubusercontent.com/35353768/37811653-878a51de-2e96-11e8-92e6-b77e8fa0c81f.png)
![drftgdg](https://user-images.githubusercontent.com/35353768/37812539-8b0a7ae6-2e9b-11e8-87b8-f127efa167c9.png)
![sdfsdf](https://user-images.githubusercontent.com/35353768/37813121-ac478f5c-2e9e-11e8-9d31-32aa2c3cab91.png)
![asda](https://user-images.githubusercontent.com/35353768/37813355-c1e97cd4-2e9f-11e8-8aee-0788664dbd5d.png)


#### Hope you like it. Please contact me if you have any suggestions
#### And please where can i make a pull request after. Thank You!

**Comment by loydjayme25** [comment]
Good day sir Mr. Project Owner,

Can i also submit my design for your project ? and i do hope that you will accept my request. Thank you and more power!

**Comment by Abdallah-Abdelazim** [comment]
@loydjayme25 sure, no problem. We can work together to make the design better.

**Comment by Abdallah-Abdelazim** [comment]
@jbeguna04  great work.

**Comment by loydjayme25** [comment]
@Abdallah-Abdelazim 
Thank you sir, i'll comment here my design later.

**Comment by jbeguna04** [comment]
Thank you. You can use those logos if you want

**Comment by Abdallah-Abdelazim** [comment]
@jbeguna04 I sent you an invitation to be added as collaborator
Now you can push what you have made

**Comment by jbeguna04** [comment]
In what file sir?

**Comment by Abdallah-Abdelazim** [comment]
Just create a new folder named Logo and put in it the images (Add separate images for each design)
I'll take the images and add them in the app and the README. Also update the play store later.

**Comment by Abdallah-Abdelazim** [comment]
I'll credit the designs to you in the README and on Play store

**Comment by jbeguna04** [comment]
Already done sir

**Comment by loydjayme25** [comment]
Hello sir, This is my simple design for the project.

![prooffinal](https://user-images.githubusercontent.com/37318022/37872152-33a1f154-3034-11e8-83d6-472188e39da6.png)

**Comment by Abdallah-Abdelazim** [comment]
@loydjayme25 Thank you for your work.
The image is nice. But don't you think it would be better if the "MY" is written in a more simpler way (for example just the "M" next to the "Y", not above)?
Also the background color could be less "colorful" 😃

**Comment by loydjayme25** [comment]
![final](https://user-images.githubusercontent.com/37318022/37918530-e3aa100c-3153-11e8-9cfa-f62fdadcabf0.png)
How about this ?

**Comment by Abdallah-Abdelazim** [comment]
@loydjayme25 Ok looks better. I've invited you as a collaborator to this repository.
Accept the invitation and you can then upload you work to the folder named "Logo".

**Comment by Abdallah-Abdelazim** [comment]
@loydjayme25 Never mind. I added the logo for you and credited it to you in the README.

**Comment by loydjayme25** [comment]
Where can i accept the invitation sir ?

**Comment by kazimyrex** [comment]
Sir I would love to run a promotion on your app through the Facebook platform to make the app more known among people on the platform
