### ISSUE TITLE
Publish on F-Droid?

### ISSUE THREAD

**Issue by IzzySoft** [Abdallah-Abdelazim/My-Notes#5]
In case you didn't know: [F-Droid](https://f-droid.org/) is THE place for open-source Android apps – so it would be great to see your app there! Would that be OK with you? Hoping for a "yes", I've already opened a [Request For Packaging](https://gitlab.com/fdroid/rfp/issues/742) (RFP) to get things going.

Regardless of yes or no, it would be a great idea to [tag your releases](https://github.com/Abdallah-Abdelazim/My-Notes/releases) (and attach the APKs to their corresponding tags). Tags would also be helpful for F-Droid, as that way new releases can be detected automatically.

Thanks in advance!

**Comment by IzzySoft** [comment]
PS: Not a show-stopper for F-Droid, but I thought you might want to know anyway: the F-Droid bot [found a minor issue with your gradlew](https://gitlab.com/fdroid/rfp/issues/742#note_107104204) you probably want to fix.

**Comment by Abdallah-Abdelazim** [comment]
OK thank you very much for your suggestion and effort. It's a great idea to publish the app on F-Droid too. I will check what issues was found and fix them.

**Comment by IzzySoft** [comment]
Thanks a lot, Abdallah! Looks good as far as I can see. Might come back to you if the "integrators" come up with some issues when building. Meanwhile, you can find your app [in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.aa.mynotes), which is used by many (but by far not all) F-Droid users.

**Comment by IzzySoft** [comment]
@Abdallah-Abdelazim just asking for an update on the tags: our "integrators" didn't yet start as tags are still absent in your repo (see my initial post).

**Comment by IzzySoft** [comment]
@Abdallah-Abdelazim ??

**Comment by Abdallah-Abdelazim** [comment]
@IzzySoft I'm really sorry for not replying all this time. I was taken away into other projects the past months. I will see what I can do about publishing on F-droid and fix the problems. Thank you for your efforts

**Comment by IzzySoft** [comment]
I gladly help if I can. Please ping me again when you've tagged the latest version.

**Comment by Abdallah-Abdelazim** [comment]
@IzzySoft I have made a release here in Github & corrected the problem in gradle as the F-droid bot suggested. What's the next step?

**Comment by IzzySoft** [comment]
Thanks! The next step is that I update the metadata in the RFP, and mark it ready to be build. I've just done that – so no we need to wait for one of our "integrators" to pick up.

Meanwhile I've set your app to auto-update in my repo. v1.5.1 was just fetched successfully, and should go online with the next sync.
